-- Snapshot schema (all migrations). Prefer supabase/migrations/ for incremental apply.
-- Initial: 20240101000000_initial_schema.sql
-- Fiscal:  20260528100000_fiscal_and_bank.sql

create table if not exists houses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  location text,
  notes text,
  fiscal_start_month int not null default 6 check (fiscal_start_month between 1 and 12),
  import_parties jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists fiscal_periods (
  id bigint generated by default as identity primary key,
  house_id bigint references houses on delete cascade not null,
  label text not null,
  start_date date not null,
  end_date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (house_id, label)
);

create table if not exists dues (
  id bigint generated by default as identity primary key,
  house_id bigint references houses on delete cascade not null,
  fiscal_period_id bigint references fiscal_periods on delete restrict not null,
  amount numeric(12,2) not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists payments (
  id bigint generated by default as identity primary key,
  house_id bigint references houses on delete cascade not null,
  fiscal_period_id bigint references fiscal_periods on delete restrict not null,
  amount numeric(12,2) not null,
  date date,
  method text,
  bank_movement_id bigint,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists bank_movements (
  id bigint generated by default as identity primary key,
  house_id bigint references houses on delete cascade not null,
  import_batch_id uuid not null,
  movement_date date not null,
  operation text,
  details text,
  amount numeric(12, 2) not null,
  currency text default 'EUR',
  source_hash text not null,
  fiscal_period_id bigint references fiscal_periods on delete set null,
  suggested_fiscal_period_id bigint references fiscal_periods on delete set null,
  match_confidence numeric(4, 3),
  match_reason text,
  linked_payment_id bigint references payments on delete set null,
  status text not null default 'unlinked'
    check (status in ('unlinked', 'suggested', 'linked', 'ignored')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (house_id, source_hash)
);

alter table payments
  drop constraint if exists payments_bank_movement_id_fkey;
alter table payments
  add constraint payments_bank_movement_id_fkey
  foreign key (bank_movement_id) references bank_movements on delete set null;

alter table houses enable row level security;
alter table fiscal_periods enable row level security;
alter table dues enable row level security;
alter table payments enable row level security;
alter table bank_movements enable row level security;

drop policy if exists "houses_select_own" on houses;
drop policy if exists "houses_insert_own" on houses;
drop policy if exists "houses_update_own" on houses;
drop policy if exists "houses_delete_own" on houses;
create policy "houses_select_own" on houses for select using (auth.uid() = user_id);
create policy "houses_insert_own" on houses for insert with check (auth.uid() = user_id);
create policy "houses_update_own" on houses for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "houses_delete_own" on houses for delete using (auth.uid() = user_id);

drop policy if exists "fiscal_periods_select_own" on fiscal_periods;
drop policy if exists "fiscal_periods_insert_own" on fiscal_periods;
drop policy if exists "fiscal_periods_update_own" on fiscal_periods;
drop policy if exists "fiscal_periods_delete_own" on fiscal_periods;
create policy "fiscal_periods_select_own" on fiscal_periods for select using (
  exists (select 1 from houses where houses.id = fiscal_periods.house_id and houses.user_id = auth.uid())
);
create policy "fiscal_periods_insert_own" on fiscal_periods for insert with check (
  exists (select 1 from houses where houses.id = fiscal_periods.house_id and houses.user_id = auth.uid())
);
create policy "fiscal_periods_update_own" on fiscal_periods for update using (
  exists (select 1 from houses where houses.id = fiscal_periods.house_id and houses.user_id = auth.uid())
);
create policy "fiscal_periods_delete_own" on fiscal_periods for delete using (
  exists (select 1 from houses where houses.id = fiscal_periods.house_id and houses.user_id = auth.uid())
);

drop policy if exists "dues_select_own" on dues;
drop policy if exists "dues_insert_own" on dues;
drop policy if exists "dues_update_own" on dues;
drop policy if exists "dues_delete_own" on dues;
create policy "dues_select_own" on dues for select using (
  exists (select 1 from houses where houses.id = dues.house_id and houses.user_id = auth.uid())
);
create policy "dues_insert_own" on dues for insert with check (
  exists (select 1 from houses where houses.id = dues.house_id and houses.user_id = auth.uid())
);
create policy "dues_update_own" on dues for update using (
  exists (select 1 from houses where houses.id = dues.house_id and houses.user_id = auth.uid())
) with check (
  exists (select 1 from houses where houses.id = dues.house_id and houses.user_id = auth.uid())
);
create policy "dues_delete_own" on dues for delete using (
  exists (select 1 from houses where houses.id = dues.house_id and houses.user_id = auth.uid())
);

drop policy if exists "payments_select_own" on payments;
drop policy if exists "payments_insert_own" on payments;
drop policy if exists "payments_update_own" on payments;
drop policy if exists "payments_delete_own" on payments;
create policy "payments_select_own" on payments for select using (
  exists (select 1 from houses where houses.id = payments.house_id and houses.user_id = auth.uid())
);
create policy "payments_insert_own" on payments for insert with check (
  exists (select 1 from houses where houses.id = payments.house_id and houses.user_id = auth.uid())
);
create policy "payments_update_own" on payments for update using (
  exists (select 1 from houses where houses.id = payments.house_id and houses.user_id = auth.uid())
) with check (
  exists (select 1 from houses where houses.id = payments.house_id and houses.user_id = auth.uid())
);
create policy "payments_delete_own" on payments for delete using (
  exists (select 1 from houses where houses.id = payments.house_id and houses.user_id = auth.uid())
);

drop policy if exists "bank_movements_select_own" on bank_movements;
drop policy if exists "bank_movements_insert_own" on bank_movements;
drop policy if exists "bank_movements_update_own" on bank_movements;
drop policy if exists "bank_movements_delete_own" on bank_movements;
create policy "bank_movements_select_own" on bank_movements for select using (
  exists (select 1 from houses where houses.id = bank_movements.house_id and houses.user_id = auth.uid())
);
create policy "bank_movements_insert_own" on bank_movements for insert with check (
  exists (select 1 from houses where houses.id = bank_movements.house_id and houses.user_id = auth.uid())
);
create policy "bank_movements_update_own" on bank_movements for update using (
  exists (select 1 from houses where houses.id = bank_movements.house_id and houses.user_id = auth.uid())
);
create policy "bank_movements_delete_own" on bank_movements for delete using (
  exists (select 1 from houses where houses.id = bank_movements.house_id and houses.user_id = auth.uid())
);

create index if not exists idx_houses_user_id on houses(user_id);
create index if not exists idx_fiscal_periods_house_id on fiscal_periods(house_id);
create index if not exists idx_dues_house_id on dues(house_id);
create index if not exists idx_dues_fiscal_period_id on dues(fiscal_period_id);
create index if not exists idx_payments_house_id on payments(house_id);
create index if not exists idx_payments_fiscal_period_id on payments(fiscal_period_id);
create index if not exists idx_bank_movements_house_id on bank_movements(house_id);

create table if not exists prior_balances (
  id bigint generated by default as identity primary key,
  house_id bigint references houses on delete cascade not null,
  fiscal_period_id bigint references fiscal_periods on delete cascade not null,
  source_period_id bigint references fiscal_periods on delete set null,
  amount numeric(12,2) not null,
  description text,
  created_at timestamptz not null default now(),
  unique (house_id, fiscal_period_id)
);

alter table prior_balances enable row level security;

drop policy if exists "prior_balances_select_own" on prior_balances;
drop policy if exists "prior_balances_insert_own" on prior_balances;
drop policy if exists "prior_balances_update_own" on prior_balances;
drop policy if exists "prior_balances_delete_own" on prior_balances;

create policy "prior_balances_select_own" on prior_balances for select using (
  exists (select 1 from houses where houses.id = prior_balances.house_id and houses.user_id = auth.uid())
);
create policy "prior_balances_insert_own" on prior_balances for insert with check (
  exists (select 1 from houses where houses.id = prior_balances.house_id and houses.user_id = auth.uid())
);
create policy "prior_balances_update_own" on prior_balances for update using (
  exists (select 1 from houses where houses.id = prior_balances.house_id and houses.user_id = auth.uid())
) with check (
  exists (select 1 from houses where houses.id = prior_balances.house_id and houses.user_id = auth.uid())
);
create policy "prior_balances_delete_own" on prior_balances for delete using (
  exists (select 1 from houses where houses.id = prior_balances.house_id and houses.user_id = auth.uid())
);

create index if not exists idx_prior_balances_house_id on prior_balances(house_id);
create index if not exists idx_prior_balances_fiscal_period_id on prior_balances(fiscal_period_id);
