create table if not exists prior_balances (
  id bigint generated by default as identity primary key,
  house_id bigint references houses on delete cascade not null,
  fiscal_period_id bigint references fiscal_periods on delete cascade not null,
  source_period_id bigint references fiscal_periods on delete set null,
  amount numeric(12,2) not null,
  description text,
  created_at timestamptz not null default now(),
  unique (house_id, fiscal_period_id)
);

alter table prior_balances enable row level security;

drop policy if exists "prior_balances_select_own" on prior_balances;
drop policy if exists "prior_balances_insert_own" on prior_balances;
drop policy if exists "prior_balances_update_own" on prior_balances;
drop policy if exists "prior_balances_delete_own" on prior_balances;

create policy "prior_balances_select_own" on prior_balances for select using (
  exists (select 1 from houses where houses.id = prior_balances.house_id and houses.user_id = auth.uid())
);
create policy "prior_balances_insert_own" on prior_balances for insert with check (
  exists (select 1 from houses where houses.id = prior_balances.house_id and houses.user_id = auth.uid())
);
create policy "prior_balances_update_own" on prior_balances for update using (
  exists (select 1 from houses where houses.id = prior_balances.house_id and houses.user_id = auth.uid())
) with check (
  exists (select 1 from houses where houses.id = prior_balances.house_id and houses.user_id = auth.uid())
);
create policy "prior_balances_delete_own" on prior_balances for delete using (
  exists (select 1 from houses where houses.id = prior_balances.house_id and houses.user_id = auth.uid())
);

create index if not exists idx_prior_balances_house_id on prior_balances(house_id);
create index if not exists idx_prior_balances_fiscal_period_id on prior_balances(fiscal_period_id);
